#!/bin/bash

# Cambio de hotspot via TG by EA7JCL & EA5GVK

NOMBRE=$(awk 'NR==2' /var/log/dato.txt)
IDSALTO=$(awk 'NR==1' /var/log/dato.txt)
PRODUCCION=$(awk 'NR==7' /etc/sslb)

function MMDVMSERVICE(){
NOMBREACT=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT nombre FROM hotspot where id = '$IDSALTO';")
MMSERVICE="/var/log/MMDVMHOTSPOT-$NOMBREACT.service"
echo "#           Configuracion by EA7JCL & BLASMAKERS &  EA5GVK.ES" > $MMSERVICE
echo "" >> $MMSERVICE
echo "[Unit]" >> $MMSERVICE
echo "Description=MMDVM_Host $NOMBREACT daemon " >> $MMSERVICE
echo "After=syslog.target network.target" >> $MMSERVICE
echo "" >> $MMSERVICE
echo "[Service]" >> $MMSERVICE
echo "User=root" >> $MMSERVICE
echo "WorkingDirectory=/opt/HOTSPOTS-ACTIVOS/$NOMBREACT/MMDVMHost/" >> $MMSERVICE
echo "RestartSec=always" >> $MMSERVICE
ruta1="/opt/HOTSPOTS-ACTIVOS/$NOMBREACT/MMDVMHost/MMDVMHost"
ruta2="/opt/HOTSPOTS-ACTIVOS/$NOMBREACT/MMDVMHost/MMDVM.ini"
echo "ExecStart=$ruta1 $ruta2" >> $MMSERVICE
echo "Restart=always" >> $MMSERVICE
echo "RestartSec=10" >> $MMSERVICE
echo "" >> $MMSERVICE
echo "[Install]" >> $MMSERVICE
echo "WantedBy=multi-user.target" >> $MMSERVICE
sudo cp /var/log/MMDVMHOTSPOT-$NOMBREACT.service /etc/systemd/system/
ordensql="INSERT INTO services (nombre,service,log) VALUES ('$NOMBREACT','MMDVMHOTSPOT-$NOMBREACT.service','/var/log/hotspots/MMDVM-$NOMBREACT');"
sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "$ordensql"
sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "UPDATE hotspot SET estado = '1' where nombre = '$NOMBREACT'";
}

function DESACTIVAR(){
sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "UPDATE hotspot SET estado = '0' where nombre = '$NOMBRE'";
sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "UPDATE hotspot SET estado = '0' where nombre = '$NOMBRE'";
sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "delete from services where nombre = '$NOMBRE'";
}

function ACTIVAR(){
ser="MMDVMHOTSPOT-$NOMBRE.service"
servicio="MMDVMHOTSPOT-$NOMBREACT.service"
systemctl daemon-reload
sudo systemctl enable $servicio
sudo systemctl start $servicio
sudo systemctl disable $ser
sudo systemctl stop $ser
sudo rm /etc/systemd/system/$ser > /dev/null 2>&1
systemctl daemon-reload
}
LOG2=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT log FROM services where nombre = '$NOMBRE';")
fecha=$(date +%Y-%m-%d)
LOG="$LOG2-$fecha.log"
if [[ $IDSALTO -gt 10 ]] && [[ $IDSALTO -lt 98 ]]
then
    SALTOANTIGUO=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT id FROM hotspot where nombre = '$NOMBRE';")
    IDSALTO=`expr $IDSALTO - 10`
    if [[ $IDSALTO -ne $SALTOANTIGUO ]]
    then
        echo "Salto dentro del rango 11 a 99" >> $LOG
        NUEVACONEXION=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT devtty FROM hotspot where id = '$IDSALTO';")
        ANTIGUACONEXION=$(sudo mysql -h localhost -u root -p@^@^@^@^ -D hblink -s -e "SELECT devtty FROM hotspot where nombre = '$NOMBRE';")
        echo "el iddesalto es $IDSALTO  $NUEVACONEXION == $ANTIGUACONEXION"
        if [[ $NUEVACONEXION == $ANTIGUACONEXION ]] 
        then
            DESACTIVAR
            MMDVMSERVICE
            echo "Reconfigurando y cambiando conexion a $NOMBREACT"  >> $LOG
            ACTIVAR
        else
            echo "TG de salto no asignado a este HOTSPOT en puerto $ANTIGUACONEXION" >> $LOG
        fi
    else
        echo "Conexion ya activa. Intenta otro TG" >> $LOG
    fi
fi
